# Numpy: Numeric computing library

- NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.
- NumPy is a python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* Efficient **(Extremly powerful) numeric computation** with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.
* High performance 

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple integers are also objects, with all the required machinery to make object work. 
We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

Official website: https://numpy.org/ 


<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


Let's start by importing the neccessary libs for numpy

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

- NumPy's main object is the homogenous multidimensional array of class narray
- It is a multidimesional table of elements , indexed by a tuple of positive integers
- Each element in numpy array has the same type, which is specified by an associated data type object (dtype)
- the dimesions of a numpy array are called **axes**
  - The number of axes an array has is called rank
- the shape of the array defines the size of the array along each of its axes returned as a tupe of integers

In [ ]:
np.array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4, 5, 6,])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [5]:
# Exercise
# Create a numpy named c array with 3 boolean values
c = np.array([True, False, True])
c

array([ True, False,  True])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
# slicing from cell 0 till the end
a[0:] 

array([1, 2, 3, 4, 5, 6])

In [8]:
# Slice the array from cell 1 to cell 3
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3, 4, 5])

In [10]:
# index in steps of 2
a[::2]

array([1, 3, 5])

In [11]:
# Exercise:
# Print every the third cell (a.k.a in steps of 3)
a[::3]

array([1, 4])

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
# sending the indexes we want to select as a list
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [13]:
a

array([1, 2, 3, 4])

**Python needs to know which data type it is to know which operations can be activated on array**

In [14]:
a.dtype

dtype('int64')

In [16]:
b.dtype

dtype('float64')

In [17]:
# Exercise
# Print the data type of c numpy array created above (has mixed integers and float values)
c.dtype

dtype('bool')

Setting data type by using the optional dtype argument 

In [18]:
# Even though the data type of the array is integers, use them as floats
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

In [19]:
np.array([1., 2., 3., 4.], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

Although numpy is mainly used for numerical values (integers, floats, dates etc...), it can also contain strings, chars and regular objects but there's no point to it...

In [175]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
# don't go string happy on numpy - it's not that smart...
d = np.array([{'a': 1}, sys])

In [151]:
d.dtype

dtype('O')

In [21]:
# Exercise
# create a numpy mixed array of integers and floats 
# What will be the dtype?
e=np.array([1, 2, 3.])
e.dtype

dtype('float64')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

- The n in __n-array__ referes to the number of dimensions in array (2D, 3D etc...)
- The __shape__ of an array is the number of elements in each dimension.


![dshapers](https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png)

In [23]:
# Given the following array
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
# What is the A.shape of the array?
A.shape

(2, 3)

In [25]:
# What is the n-dimension of the array? (hint: ndim)
A.ndim

2

In [26]:
# returns the amount of elements (cells) in array
A.size

6

In [31]:
oned = []
twod = [
    [],
    []
]
threed = [
    [
        [],
        []
    ],
    [
        [],
        []
    ]
]

In [30]:
B = np.array(
[
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
print('Num of dimensions: ', B.ndim)
print('Num of elements: ', B.size)
print('Shape: ', B.shape)

Num of dimensions:  3
Num of elements:  12
Shape:  (2, 2, 3)


Exercise: Try to answer these before checking them in numpy
 - How many dimension does B have?
 - What is the shape of B?
 - How many elements in array?

In [32]:
# If the shape isn't consistent, it'll just fall back to regular Python objects:
C = np.array(
[
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/home/a/.local/lib/python3.7/site-packages/ipykernel_launcher.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  if __name__ == '__main__':


In [33]:
C.dtype

dtype('O')

In [34]:
C.shape

(2,)

In [35]:
C.size

2

In [36]:
type(C[0])

list

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices (2X2)

        array[row][col]
        
        array[dim1, dim2, dim3 ... dimn]     
        

In [37]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [178]:
A[1] # selects row in index # 1

array([4, 5, 6])

In [181]:
A[1][0] # selects cell in row index # 1 and column index # 0

4

In [182]:
#Exercise: Extract the values 1 and 9 from array

Using the multiple dimensional selection in numpy
d1-4 represent the dimensions

    arrayName[d1, d2, d3, d4]
    

In [185]:
# for dim1 (row) 1 and dim2 (column) 0 
A[1, 0]

4

In [186]:
# The advantage of using dim selecting is that we can also slice it by dimesion
# here we select from dimesion 1 (rows) all rows up to 2
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# select every row (from dimension 1) then select the 2 columns (dimension 2)
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

Assign new array into a numpy array

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
# replace row 1 with given array provided it has the same dimensions.
A[1] = np.array([10, 10, 10])

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [190]:
# Assign a number to every element in the row.
A[2] = 99

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

NumPy has a huge library of mathamatical and statistical operations we can do on arrays

In [51]:
a = np.array([1, 2, 3, 4])

In [52]:
a.sum()

10

In [53]:
a.mean()

2.5

In [54]:
a.std() # standard deviation

1.118033988749895

In [191]:
a.var() # varians

2.9166666666666665

In [56]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [57]:
A.sum()

45

In [58]:
A.mean()

5.0

In [59]:
A.std()

2.581988897471611

Numpy array can also perform operations on axis

In [60]:
A.sum(axis=0)

array([12, 15, 18])

In [61]:
A.sum(axis=1)

array([ 6, 15, 24])

In [62]:
A.mean(axis=0)

array([4., 5., 6.])

In [63]:
A.mean(axis=1)

array([2., 5., 8.])

In [64]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [65]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...